# Generated by Django 4.1.3 on 2022-11-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=50)),
                ("phase", models.CharField(max_length=50)),
            ],
        ),
    ]
