# Generated by Django 4.1.3 on 2022-11-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card", old_name="dropdown", new_name="phase",
        ),
    ]
