# Generated by Django 4.1.3 on 2022-11-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0002_card_step"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="step",),
    ]
